# Generated by Django 4.2.16 on 2026-03-15 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('capital_usd', models.FloatField()),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pairs_scanned', models.IntegerField(default=0)),
                ('signals_found', models.IntegerField(default=0)),
                ('signals_sent', models.IntegerField(default=0)),
                ('btc_score', models.IntegerField(default=0)),
                ('btc_price', models.FloatField(default=0)),
                ('btc_trend', models.CharField(default='', max_length=40)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], db_index=True, max_length=4)),
                ('grade', models.CharField(choices=[('ULTRA', 'Ultra'), ('STRONG', 'Strong'), ('STANDARD', 'Standard')], db_index=True, max_length=10)),
                ('confidence', models.IntegerField()),
                ('confluence', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('tp1', models.FloatField()),
                ('tp2', models.FloatField()),
                ('tp3', models.FloatField()),
                ('sl', models.FloatField()),
                ('gain_24h', models.FloatField()),
                ('rsi', models.FloatField()),
                ('btc_score', models.IntegerField()),
                ('btc_trend', models.CharField(max_length=40)),
                ('factors', models.TextField(default='[]')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('TP1', 'TP1 Hit'), ('TP2', 'TP2 Hit'), ('TP3', 'TP3 Hit'), ('SL', 'Stop Loss'), ('BE', 'Breakeven'), ('MANUAL', 'Manual')], db_index=True, default='PENDING', max_length=10)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('profit_pct', models.FloatField(blank=True, null=True)),
                ('auto_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'signal'], name='dashboard_s_created_c8acb5_idx'), models.Index(fields=['symbol', 'created_at'], name='dashboard_s_symbol_0fd584_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('sentiment', models.CharField(default='neutral', max_length=10)),
                ('published', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currencies', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ['-published'],
                'unique_together': {('title', 'source')},
            },
        ),
    ]
