# Generated by Django 4.2.16 on 2026-03-26 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTradeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures')], default='spot', max_length=10)),
                ('capital_usdt', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('risk_per_trade', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('max_trades_day', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('trades_today', models.PositiveIntegerField(default=0)),
                ('total_auto_trades', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Trade State',
                'verbose_name_plural': 'Auto Trade State',
            },
        ),
    ]
