# Generated by Django 4.2.16 on 2026-03-26 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_autotradestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='capital_usdt',
            field=models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='max_trades_day',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='risk_per_trade',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='signalrecord',
            name='grade',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='signalrecord',
            index=models.Index(fields=['outcome', 'created_at'], name='dashboard_s_outcome_3423c3_idx'),
        ),
    ]
