# Generated by Django 4.2.16 on 2026-03-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_signalrecord_notes_alter_autotradestate_capital_usdt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotradestate',
            name='mode',
            field=models.CharField(choices=[('spot', 'Spot'), ('futures', 'Futures'), ('both', 'Both (Spot + Futures)')], default='spot', max_length=10),
        ),
    ]
