# Generated by Django 4.2.16 on 2026-03-26 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_autotradestate_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='autotradestate',
            name='futures_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='futures_max_trades',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='futures_risk',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='futures_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='futures_trades_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='spot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='spot_max_trades',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='spot_risk',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='spot_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='autotradestate',
            name='spot_trades_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='capital_usdt',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='max_trades_day',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='mode',
            field=models.CharField(default='spot', max_length=10),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='risk_per_trade',
            field=models.FloatField(default=2.0),
        ),
    ]
