# Generated by Django 4.2.16 on 2026-03-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_autotradestate_futures_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotradestate',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='futures_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='spot_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
