# Generated by Django 4.2.16 on 2026-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_autotradestate_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotradestate',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='futures_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='autotradestate',
            name='spot_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
