# Generated by Django 4.2.16 on 2026-04-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_autotradestate_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalpPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=10)),
                ('qty', models.FloatField(default=0)),
                ('entry', models.FloatField(default=0)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('close_reason', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
