# Generated by Django 4.2.16 on 2026-04-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_autotradestate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrecord',
            name='score_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
