# Generated by Django 4.2.16 on 2026-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_scalpposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalrecord',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Scoring breakdown per factor'),
        ),
        migrations.AddField(
            model_name='signalrecord',
            name='trigger_type',
            field=models.CharField(blank=True, default='', help_text='Sweep / Breakout', max_length=20),
        ),
    ]
